name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Set up git repository
        uses: actions/checkout@v2
      - name: pwdd
        run: pwd        
      - name: Install zsh
        if: runner.os == 'Linux'
        run: sudo apt-get update; sudo apt-get install zsh neofetch;
      - name: Install neofetch for Mac
        if: runner.os == 'Macos'
        run: brew install neofetch;
      - name: Deps
        run: sudo chsh -s /bin/zsh; sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"; cp ./.zshrc ~/.zshrc; zsh
      - name: Test installer
        run: ls -lha ~
      - name: pwda
        run: pwd && zsh        
      - name: Check syntax
        run: zsh ~/.zshrc
